# Read robochef DB credentials from Vault
data "vault_generic_secret" "robochef_db" {
  path = "secret/robochef-db"
}

# Read chillbot API key from Vault
data "vault_generic_secret" "chillbot_api" {
  path = "secret/chillbot-api"
}

# Use the secrets to generate a config file (simulating app deployment)
resource "local_file" "app_config" {
  filename        = "/tmp/robochef-app-config.txt"
  file_permission = "0600"
  content = <<-EOT
    # robochef.co application config
    # Generated by Terraform + Vault
    db_host=${data.vault_generic_secret.robochef_db.data["host"]}
    db_user=${data.vault_generic_secret.robochef_db.data["username"]}
    # password is NOT written to this file in plaintext
  EOT
}

resource "local_file" "chillbot_config" {
  filename        = "/tmp/chillbot-api-config.txt"
  file_permission = "0600"
  content = "region=${data.vault_generic_secret.chillbot_api.data["region"]}\n"
}
