# Site configuration generated by Terraform
# Owner: ${owner}
# Generated: ${generated_at}

server {
    server_name ${domain};
    listen      ${port};
    root        /var/www/${app_name};

    location / {
        proxy_pass http://127.0.0.1:${app_port};
    }

    # Enabled features:
%{ for feature in features ~}
    # - ${feature}
%{ endfor ~}
}
